App\Domain\Training:
  type: entity
  table: trainings
  id:
    id:
      type: string
      generator:
        strategy: NONE
  fields:
    name:
      type: string
      length: 50
    date:
      type: string
      nullable: true
    planId:
      type: string
      length: 50
      nullable: true
