App\Domain\Plan:
  type: entity
  table: plans
  id:
    id:
      type: string
      generator:
        strategy: NONE
  fields:
    name:
      type: string
      length: 50
  manyToMany:
    exercises:
      targetEntity: Activity
      joinTable:
        name: plan_activities
        joinColumns:
          plan_id:
            referencedColumnName: id
        inverseJoinColumns:
          activity_id:
            referencedColumnName: id
      cascade:
        - persist
