App\Domain\Activity:
  type: entity
  table: activities
  id:
    id:
      type: string
      generator:
        strategy: NONE
  fields:
    weight:
      type: float
    repeats:
      type: integer
    exerciseId:
      type: string
      length: 50
    trainingId:
      type: string
      length: 50
      nullable: true
