App\Training\Domain\Activity:
  type: entity
  table: training_activities
  id:
    id:
      type: string
      generator:
        strategy: NONE
  fields:
    weight:
      type: float
    repeats:
      type: integer
    exerciseId:
      type: string
      length: 50
    date:
      type: string
      length: 19
