App\Training\Domain\Training:
  type: entity
  table: trainings
  id:
    id:
      type: string
      generator:
        strategy: NONE
  fields:
    name:
      type: string
      length: 50
    status:
      type: string
      length: 10
      options:
        default: planned
    date:
      type: string
      nullable: true
    planId:
      type: string
      length: 50
      nullable: true
  manyToMany:
    activities:
      targetEntity: Activity
      joinTable:
        name: join_training_activities
        joinColumns:
          training_id:
            referencedColumnName: id
        inverseJoinColumns:
          activity_id:
            referencedColumnName: id
      cascade:
        - persist
